music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'

urlpatterns = [
    # /music/
    url(r'^$', views.IndexView.as_view(), name='index'),

    # /music/<album_id>/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailsView.as_view(), name='detail'),
    # url(r'^music/(?P<album_id>[0-9]+)/$', views.detail, name='detail'),

    # /music/album/add/
    url(r'album/add/$', views.AlbumCreate.as_view(), name='album-add'),

]

website/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

music/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Album(models.Model):
    artist = models.CharField(max_length=250)
    albm_title = models.CharField(max_length=500)
    gener = models.CharField(max_length=100)
    alb_logo = models.CharField(max_length=1000)

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.albm_title + ' - ' + self.artist


class Song(models.Model):
    albm = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

music/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from .models import Album


class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'all_albums'

    def get_queryset(self):
        return Album.objects.all()


class DetailsView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'

class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'albm_title', 'gener', 'alb_logo']

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Viberr{% endblock %}</title>
    <!---Loads the path to your static files--->
        {% load staticfiles %}
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.2.1.min.js"></script>
        <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>
    <!-- Navigation Menu -->
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <!-- Header -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'music:index' %}">Viberr</a>
            </div>

            <!-- Items -->
            <div class="collapse navbar-collapse" id="topNavBar">
                <ul class="nav navbar-nav">
                    <li class="{% block  albums_active %}active{% endblock %}">
                        <a href="{% url 'music:index' %}">
                            <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;Albums
                        </a>
                    </li>

                    <li class="">
                        <a href="#">
                            <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;Songs
                        </a>
                    </li>
                </ul>
                <form class="navbar-form navbar-left" role="search" method="get" action="#">
                    <div class="form-group">
                        <input type="text" class="form-control" name="q" value="">
                    </div>
                    <button type="submit" class="btn btn-default">Search</button>
                </form>

                <ul class="nav navbar-nav navbar-right">
                    <li class="">
                        <a href="{% url 'music:index' %}">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;Add Album
                        </a>
                    </li>

                    <li class="">
                        <a href="{% url 'music:index' %}">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;Logout
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    {% block body %}
    
    {% endblock %}

</body>
</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}Album Details{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row content" >
      <div class="col-xs-6 col-md-3" style="z-index: 1;" >
        <div class="thumbnail" style="max-height: 600px; max-width: 250px;">
          <img src="{{ album.alb_logo }}" alt="{{ album.albm_title }}">
          <div class="caption">
                <h3>{{ album.albm_title }} &nbsp; <span style="color: rgba(24,16,21,0.45)">{{ album.gener }}</span></h3>
                <h4>{{ album.artist }}</h4>
          </div>
        </div>
      </div>

    <div class="col-sm-9" style="margin-bottom: 10px;">
        <button class="btn btn-primary" type="button">View All</button>&nbsp;&nbsp;&nbsp;&nbsp;
        <a href="#">Add New Song</a>
    </div>

    <div class="container col-sm-9" style="background: white">
      <h2>All song</h2>
    {#  <p>The .table-responsive class creates a responsive table which will scroll horizontally on small devices (under 768px). When viewing on anything larger than 768px wide, there is no difference:</p>#}
      <div class="table-responsive">
      <table class="table table-hover table-striped">
        <thead>
          <tr>
            <th>#</th>
            <th>Title</th>
            <th>Audio File</th>
            <th>Favorite</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
        {% for song in album.song_set.all %}
          <tr>
            <td>1</td>
            <td>{{ song.song_title  }}</td>
            <td><button type="button" class="btn btn-success"><span class="glyphicon glyphicon-play"></span>&nbsp;Play</button></td>
            <td>
                {% if song.is_favorite %}
                    <a href="#" ><span class="glyphicon glyphicon-star"></span></a>
                {% else %}
                    <a href="#"><span class="glyphicon glyphicon-star-empty "></span></a>
                {% endif %}</td>
            <td><button type="button" class="btn btn-danger"><span class="glyphicon glyphicon-remove"></span>&nbsp;Delete</button></td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
      </div>
    </div>
    </div>
</div>
{% endblock %}

music/templates/music/index.html
{% extends 'music/base.html' %}

{% block body %}
    <div class="row" style="margin-left: 10px; margin-right: 10px;">
        {% for album in all_albums %}
          <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
              <img src="{{ album.alb_logo }}" alt="Album Cover">
              <div class="caption">
                <h3>{{ album.albm_title }}</h3>
                  <h5><strong>{{ album.artist }}</strong></h5>
                <p>
                    <a href="{% url 'music:detail' album.id %}" class="btn btn-primary" role="button">View Details</a>
                        <button type="button" class="btn btn-default btn-sm"><span class="glyphicon glyphicon-trash"></span></button>
                    <button type="button" class="btn btn-default btn-sm"><span class="glyphicon glyphicon-star-empty"></span></button>
                </a>
                </p>
              </div>
            </div>
          </div>
    {% endfor %}
    </div>
{% endblock %}